load("GiaB.rda")
truediff18 <- intersect(diff18, snps18)
truediff19 <- intersect(diff19, snps19)
truediff20 <- intersect(diff20, snps20)
truediff21 <- intersect(diff21, snps21)
truediff22 <- intersect(diff22, snps22)
falsediff18 <- setdiff(diff18, truediff18)
falsediff19 <- setdiff(diff19, truediff19)
falsediff20 <- setdiff(diff20, truediff20)
falsediff21 <- setdiff(diff21, truediff21)
falsediff22 <- setdiff(diff22, truediff22)
truediff18 <- rbind(truediff18, rep("true",length(truediff18)), rep("chr18", length(truediff18)))
truediff19 <- rbind(truediff19, rep("true",length(truediff19)), rep("chr19", length(truediff19)))
truediff20 <- rbind(truediff20, rep("true",length(truediff20)), rep("chr20", length(truediff20)))
truediff21 <- rbind(truediff21, rep("true",length(truediff21)), rep("chr21", length(truediff21)))
truediff22 <- rbind(truediff22, rep("true",length(truediff22)), rep("chr22", length(truediff22)))
falsediff18 <- rbind(falsediff18, rep("false",length(falsediff18)), rep("chr18", length(falsediff18)))
falsediff19 <- rbind(falsediff19, rep("false",length(falsediff19)), rep("chr19", length(falsediff19)))
falsediff20 <- rbind(falsediff20, rep("false",length(falsediff20)), rep("chr20", length(falsediff20)))
falsediff21 <- rbind(falsediff21, rep("false",length(falsediff21)), rep("chr21", length(falsediff21)))
falsediff22 <- rbind(falsediff22, rep("false",length(falsediff22)), rep("chr22", length(falsediff22)))
result <- cbind(truediff18, truediff19, truediff20, truediff21, truediff22)
result2 <- cbind(falsediff18, falsediff19, falsediff20, falsediff21, falsediff22)
row.names(result) <- c("Site", "Snp", "Chr")
row.names(result2) <- c("Site", "Snp", "Chr")
final_result <- cbind(result, result2)
GiaB_dataset <- data.table(t(final_result))
GiaB_dataset$Site <- as.numeric(GiaB_dataset$Site)
save(GiaB_dataset, file="GiaB_dataset.rda")
load("upennmed.rda")
truediff19 <- intersect(diff19, snps19)
truediff20 <- intersect(diff20, snps20)
truediff21 <- intersect(diff21, snps21)
truediff22 <- intersect(diff22, snps22)
falsediff19 <- setdiff(diff19, truediff19)
falsediff20 <- setdiff(diff20, truediff20)
falsediff21 <- setdiff(diff21, truediff21)
falsediff22 <- setdiff(diff22, truediff22)
truediff19 <- rbind(truediff19, rep("true",length(truediff19)), rep("chr19", length(truediff19)))
truediff20 <- rbind(truediff20, rep("true",length(truediff20)), rep("chr20", length(truediff20)))
truediff21 <- rbind(truediff21, rep("true",length(truediff21)), rep("chr21", length(truediff21)))
truediff22 <- rbind(truediff22, rep("true",length(truediff22)), rep("chr22", length(truediff22)))
falsediff19 <- rbind(falsediff19, rep("false",length(falsediff19)), rep("chr19", length(falsediff19)))
falsediff20 <- rbind(falsediff20, rep("false",length(falsediff20)), rep("chr20", length(falsediff20)))
falsediff21 <- rbind(falsediff21, rep("false",length(falsediff21)), rep("chr21", length(falsediff21)))
falsediff22 <- rbind(falsediff22, rep("false",length(falsediff22)), rep("chr22", length(falsediff22)))
result <- cbind(truediff19, truediff20, truediff21, truediff22)
result2 <- cbind(falsediff19, falsediff20, falsediff21, falsediff22)
row.names(result) <- c("Site", "Snp", "Chr")
row.names(result2) <- c("Site", "Snp", "Chr")
final_result <- cbind(result, result2)
upenn_dataset <- data.table(t(final_result))
upenn_dataset$Site <- as.numeric(upenn_dataset$Site)
save(upenn_dataset, file="upenn_dataset.rda")